language: c 

install:
  - make install

compiler:
  - gcc
  - clang

notifications:
  email:
    recipients:
      - predic@gmail.com
    on_success: always
    on_failure: always

script:
  ./helloworld


